name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

    paths:
      - 'idr-client/**'
      - '.github/workflows/build_idr_client.yml'

env:
  REGISTRY: docker.io
  IMAGE_NAME: dsiviy/idr-client

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate variables
        run: |
          export BUILD_DATE=$(date +"%Y%m%d")
          export SHORT_HASH=$(git rev-parse --short HEAD)
          echo VERSION=$BUILD_DATE-$GITHUB_RUN_NUMBER-$SHORT_HASH >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.VERSION }}
          labels: |
            org.opencontainers.image.version=${{ env.VERSION }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./radius-listener/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
